name: CI

on:
  pull_request:
    branches: [main, dev, stag, uat]
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache uv and pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: $HOME/.cargo/bin/uv pip install .[dev]

      - name: Run black check
        run: $HOME/.cargo/bin/uv run black --check .

      - name: Run isort check
        run: $HOME/.cargo/bin/uv run isort --check-only .

      - name: Run tests
        run: $HOME/.cargo/bin/uv run pytest

      - name: Run linter
        run: |
          $HOME/.cargo/bin/uv pip install ruff
          $HOME/.cargo/bin/uv run ruff .
          
